<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationIcon>testing.ico</ApplicationIcon>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<BaseOutputPath>D:\pos\Free Soft\pos\pos\bin</BaseOutputPath>
		<ProduceReferenceAssembly>True</ProduceReferenceAssembly>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<Title>Smart Cashier</Title>
		<AssemblyName>Smart Cashier</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Settings\Settings.config" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Settings.config">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Settings\Settings.config">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="testing.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.Reporting" Version="2.1.0" />
		<PackageReference Include="DevExpress.Aspire.Reporting" Version="25.1.6" />
		<PackageReference Include="DevExpress.Reporting.Core" Version="25.1.6" />
		<PackageReference Include="DevExpress.Win.Design" Version="25.1.6" />
		<PackageReference Include="FastReport.OpenSource" Version="2026.1.2" />
		<PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.7" />
		<PackageReference Include="Humanizer" Version="2.14.1" />
		<PackageReference Include="LiveCharts.WinForms" Version="0.9.7.1" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
		<PackageReference Include="Microsoft.Reporting.WinForms.v11" Version="1.0.0" />
		<PackageReference Include="Syncfusion.Chart.Windows" Version="29.1.40" />
		<PackageReference Include="Syncfusion.Grid.Grouping.Windows" Version="29.1.40" />
		<PackageReference Include="Syncfusion.Grid.Windows" Version="29.1.40" />
		<PackageReference Include="Syncfusion.SfDataGrid.WinForms" Version="29.1.40" />
		<PackageReference Include="Syncfusion.SfSmithChart.WinForms" Version="29.1.40" />
		<PackageReference Include="Syncfusion.Tools.Windows" Version="29.1.40" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.1" />
		<PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
		<PackageReference Include="System.Management" Version="8.0.1" />
		<PackageReference Include="Zen.Barcode.Rendering.Framework" Version="3.1.10729.1" />
		<PackageReference Include="ZXing.Net" Version="0.16.10" />
		<PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.13" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="DAL\DataSetA4.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>DataSetA4.xsd</DependentUpon>
		</Compile>
		<Compile Update="DAL\DataSetPartesReport.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>DataSetPartesReport.xsd</DependentUpon>
		</Compile>
		<Compile Update="DAL\DataSetPay.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>DataSetPay.xsd</DependentUpon>
		</Compile>
		<Compile Update="DAL\DataSet_A5.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>DataSet_A5.xsd</DependentUpon>
		</Compile>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<Service Include="{c0c07587-41a7-46c8-8fbd-3f9c8ebe2ddc}" />
	</ItemGroup>

	<ItemGroup>
		<None Update="DAL\DataSetA4.xsd">
			<Generator>MSDataSetGenerator</Generator>
			<LastGenOutput>DataSetA4.Designer.cs</LastGenOutput>
		</None>
		<None Update="DAL\DataSetPartesReport.xsd">
		  <Generator>MSDataSetGenerator</Generator>
		  <LastGenOutput>DataSetPartesReport.Designer.cs</LastGenOutput>
		</None>
		<None Update="DAL\DataSetPay.xsd">
			<Generator>MSDataSetGenerator</Generator>
			<LastGenOutput>DataSetPay.Designer.cs</LastGenOutput>
		</None>
		<None Update="DAL\DataSet_A5.xsd">
			<Generator>MSDataSetGenerator</Generator>
			<LastGenOutput>DataSet_A5.Designer.cs</LastGenOutput>
		</None>
		<None Update="Database\FullBackup.bak">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Database\NewDatabase.bak">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Database\NewDatabase.bak">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
